version: '3'
services:
  mall-admin:
    image: crpi-4z4v1n5g8hbg9g3x.cn-hangzhou.personal.cr.aliyuncs.com/beilv-agent/mall-admin:latest
    container_name: mall-admin
    ports:
      - 18080:8080
    volumes:
      - /root/install/mall/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - 'SPRING_PROFILES_ACTIVE=prod'
    external_links:
      - beilv_agent_mysql:db #可以用db这个域名访问mysql服务
      - beilv_agent_minio:minio #可以用minio这个域名访问minio服务
  mall-portal:
    image: crpi-4z4v1n5g8hbg9g3x.cn-hangzhou.personal.cr.aliyuncs.com/beilv-agent/mall-portal:latest
    container_name: mall-portal
    ports:
      - 18085:8085
    volumes:
      - /root/install/mall/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - 'SPRING_PROFILES_ACTIVE=prod'
    external_links:
      - beilv_agent_redis:redis #可以用redis这个域名访问redis服务
      - beilv_agent_mongo:mongo #可以用mongo这个域名访问mongo服务
      - beilv_agent_mysql:db #可以用db这个域名访问mysql服务
      - beilv_agent_rabbitmq:rabbitmq #可以用rabbitmq这个域名访问rabbitmq服务
      - beilv_agent_minio:minio #可以用minio这个域名访问minio服务
