server:
  port: 8085

spring:
  application:
    name: mall-portal
  profiles:
    active: dev #默认为开发环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Spring Mail 配置 - 自动适配所有邮件服务商
  mail:
    # 基础配置 - 通过环境变量自动适配
    host: ${MAIL_HOST:smtp.exmail.qq.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:vcode@xrateverse.com}
    password: ${MAIL_PASSWORD:NNyqSi67bLuGLzpv}
    protocol: ${MAIL_PROTOCOL:smtps}
    default-encoding: UTF-8
    test-connection: false

    # 高级配置 - 兼容所有邮件服务商
    properties:
      mail:
        debug: ${MAIL_DEBUG:false}
        smtp:
          auth: true
          timeout: ${MAIL_TIMEOUT_SECONDS:30}000
          connectiontimeout: ${MAIL_TIMEOUT_SECONDS:30}000
          writetimeout: ${MAIL_TIMEOUT_SECONDS:30}000
          # SSL/TLS 配置 - 自动适配
          ssl:
            enable: ${MAIL_SSL_ENABLE:true}
            trust: "*"
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:false}
            required: ${MAIL_STARTTLS_REQUIRED:false}
          # SSL Socket Factory (适用于465端口)
          socketFactory:
            class: ${MAIL_SOCKET_FACTORY_CLASS:javax.net.ssl.SSLSocketFactory}
            port: ${MAIL_PORT:465}
            fallback: false

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ${JWT_SECRET:beilv-ai-mall-portal-secret-key-256-bits-change-in-production} #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)
  refresh-expiration: 604800 #刷新token超期限时间(60*60*24*7)
  issuer: beilv-ai
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /v3/api-docs/*
      - /*/*.html
      - /*/*.js
      - /*/*.css
      - /*/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /alipay/**
      - /api/auth/**
      - /api/test/**

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
    # 用于配置tag和operation的展开方式，这里配置为都不展开
    doc-expansion: 'none'
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  group-configs:
    - group: 'mall-portal'
      packages-to-scan: com.macro.mall.portal.controller

# 自定义redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

mongo:
  insert:
    sqlEnable: true # 用于控制是否通过数据库数据来插入mongo

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue

# 邮件配置 - 支持所有主流邮件服务商
mail:
  from: ${MAIL_FROM:Xrateverse <vcode@xrateverse.com>}
  from-name: ${MAIL_FROM_NAME:Xrateverse}
  from-address: ${MAIL_FROM_ADDRESS:vcode@xrateverse.com}
  debug: ${MAIL_DEBUG:false}
  verification-code:
    expire-minutes: 5
    template: verification-code
  # 邮件发送配置
  async-enabled: ${MAIL_ASYNC_ENABLED:false}
  retry-count: ${MAIL_RETRY_COUNT:3}
  timeout-seconds: ${MAIL_TIMEOUT_SECONDS:30}


# 邮件服务商预设配置
mail-providers:
  # 腾讯企业邮箱 (推荐)
  tencent-exmail:
    host: smtp.exmail.qq.com
    port: 465
    protocol: smtps
    ssl-enable: true
    starttls-enable: false
    socket-factory-class: javax.net.ssl.SSLSocketFactory
    description: "腾讯企业邮箱 - 稳定可靠"

  # QQ邮箱
  qq:
    host: smtp.qq.com
    port: 587
    protocol: smtp
    ssl-enable: false
    starttls-enable: true
    starttls-required: true
    description: "QQ邮箱 - 个人用户"

  # 网易邮箱
  netease-163:
    host: smtp.163.com
    port: 25
    protocol: smtp
    ssl-enable: false
    starttls-enable: false
    description: "网易163邮箱 - 简单配置"

  # 网易企业邮箱
  netease-qiye:
    host: smtp.ym.163.com
    port: 994
    protocol: smtps
    ssl-enable: true
    starttls-enable: false
    socket-factory-class: javax.net.ssl.SSLSocketFactory
    description: "网易企业邮箱"

  # Gmail (国外)
  gmail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    ssl-enable: false
    starttls-enable: true
    starttls-required: true
    description: "Gmail - 需要应用专用密码"

  # Outlook/Hotmail
  outlook:
    host: smtp-mail.outlook.com
    port: 587
    protocol: smtp
    ssl-enable: false
    starttls-enable: true
    starttls-required: true
    description: "Outlook/Hotmail邮箱"

  # 阿里云邮件推送
  aliyun:
    host: smtpdm.aliyun.com
    port: 25
    protocol: smtp
    ssl-enable: false
    starttls-enable: false
    description: "阿里云邮件推送服务"

  # 新浪邮箱
  sina:
    host: smtp.sina.com
    port: 25
    protocol: smtp
    ssl-enable: false
    starttls-enable: false
    description: "新浪邮箱"

  # 搜狐邮箱
  sohu:
    host: smtp.sohu.com
    port: 25
    protocol: smtp
    ssl-enable: false
    starttls-enable: false
    description: "搜狐邮箱"

# 验证码配置
verification-code:
  length: 6 # 验证码长度
  expire-minutes: 5 # 验证码有效期（分钟）
  send-interval-seconds: 60 # 发送间隔（秒）
  max-send-per-day: 10 # 每日最大发送次数
  type: NUMERIC # 验证码类型：NUMERIC、LETTER、MIXED

# OAuth2客户端配置
oauth2:
  client:
    wechat:
      app-id: ${WECHAT_APP_ID:your-wechat-app-id}
      app-secret: ${WECHAT_APP_SECRET:your-wechat-app-secret}
      redirect-uri: ${WECHAT_REDIRECT_URI:http://localhost:8085/api/auth/oauth2/callback/wechat}
    google:
      client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
      client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
      redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8085/api/auth/oauth2/callback/google}
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
    auth-success-redirect: ${FRONTEND_AUTH_SUCCESS_REDIRECT:/auth/success}
    auth-error-redirect: ${FRONTEND_AUTH_ERROR_REDIRECT:/auth/error}

